#!/bin/bash
#1 获取输入参数个数
pcount=$#
echo pcount=$pcount
if((pcount==0)); then
echo no args;
exit;
fi

#2 获取文件名称
p1=$1
fname=`basename $p1`
echo fname=$fname

#3 获取上级目录到绝对路径
pdir=`cd -P $(dirname $p1); pwd`
echo pdir=$pdir

#4 获取当前用户名称
user=`whoami`
echo user=$user

#5 循环 112 113
for((host=112; host<=113; host++)); do
		echo --------------- linux$host ----------------
		echo $pdir/$fname $user@linux$host:$pdir
        rsync -rvl $pdir/$fname $user@linux$host:$pdir
done



