#!/bin/bash
#1 获取输入参数个数
pcount=$#
if((pcount==0));then
        echo no args;
        exit;
fi

echo -------------localhost----------
# 本机执行输入的所有参数    $@表示所有参数
$@

echo ----------hadoop-lc $@---------
ssh hadoop-lc $@
echo ----------hadoop-al $@---------
ssh hadoop-al $@

#5 循环
# for((host=111; host<=115; host++)); do
        # echo ----------hadoop$host $@---------
        # ssh hadoop$host $@
# done

